INSERT INTO researchAgreement (shipName, weightData, industryFilter, strategicFilter, tacticalFilter)
VALUES
('AC721-A', 10, 'Dawn Accord', 'Strategy and Support', 'Direct-Fire Weapons'),
('AC721-B', 10, 'Dawn Accord', 'Strategy and Support', 'Projectile Weapons'),
('AC721-D', 10, 'Dawn Accord', 'Strategy and Support',NULL),
('Aldabra-A', 5, 'Noma', 'Outstanding Firepower,Sustained Combat', 'Direct-Fire Weapons'),
('Aldabra-B', 5, 'Noma', 'Outstanding Firepower,Sustained Combat', 'Direct-Fire Weapons'),
('B192 Newland', 10, 'Jupiter Industries', 'Strategy And Support,Fighter & Corvette', 'Direct-Fire Weapons'),
('Balancer Anderson SC020', 10, 'Antonios', 'Sustained Combat,Fighter & Corvette', 'Direct-Fire Weapons'),
('Bullfrog-A', 10, 'Noma', 'Outstanding Firepower,Fighter & Corvette', 'Projectile Weapons'),
('Callisto-A', 2, 'Jupiter Industries', 'Outstanding Firepower', 'Projectile Weapons'),
('Callisto-B', 2, 'Jupiter Industries', 'Outstanding Firepower', 'Projectile Weapons'),
('Callisto-C', 2, 'Jupiter Industries', NULL, 'Projectile Weapons'),
('Carillion-A', 10, 'Antonios', 'Sustained Combat,Strategy And Support', 'Direct-Fire Weapons'),
('Carillion-B', 10, 'Antonios', 'Strategy And Support', 'Direct-Fire Weapons'),
('Carillion-C', 5, 'Antonios', 'Sustained Combat', 'Direct-Fire Weapons'),
('CAS066-A', 10, 'Dawn Accord', 'Outstanding Firepower,Sustained Combat', 'Projectile Weapons'),
('CAS066-B', 10, 'Dawn Accord', 'Outstanding Firepower', 'Direct-Fire Weapons'),
('CAS066-C', 10, 'Dawn Accord', NULL, NULL),
('Cellular Defender', 5, 'Antonios', 'Outstanding Firepower,Fighter & Corvette', 'Projectile Weapons'),
('Ceres-A', 10, 'Jupiter Industries', 'Strategy and Support', NULL),
('Ceres-B', 10, 'Jupiter Industries', 'Strategy and Support', NULL),
('Ceres-C', 10, 'Jupiter Industries', 'Strategy and Support', NULL),
('Chimera-A', 5, 'Noma', 'Outstanding Firepower,Sustained Combat', 'Direct-Fire Weapons'),
('Chimera-B', 5, 'Noma', 'Outstanding Firepower,Sustained Combat', 'Direct-Fire Weapons'),
('Chimera-C', 5, 'Noma', 'Sustained Combat', 'Direct-Fire Weapons'),
('Conamara Chaos-A', 5, 'Jupiter Industries', 'Strategy and Support', 'Direct-Fire Weapons'),
('Conamara Chaos-B', 5, 'Jupiter Industries', 'Outstanding Firepower', 'Direct-Fire Weapons'),
('Constantine the Great', 2, 'Antonios', 'Outstanding Firepower', 'Direct-Fire Weapons'),
('CV-II003', 10, 'Dawn Accord', 'Strategy and Support,Fighter & Corvette', 'Direct-Fire Weapons'),
('CV-M011-A', 10, 'Dawn Accord', 'Outstanding Firepower,Sustained Combat,Strategy And Support,Fighter & Corvette', 'Projectile Weapons'),
('CV-M011-B', 10, 'Dawn Accord', 'Fighter & Corvette', 'Direct-Fire Weapons'),
('CV-T800', 5, 'Dawn Accord', 'Outstanding Firepower,Strategy and Support,Fighter & Corvette', 'Direct-Fire Weapons'),
('CV3000', 2, 'Dawn Accord', 'Strategy and Support', NULL),
('Eris I-A', 10, 'Jupiter Industries', 'Strategy and Support', 'Direct-Fire Weapons'),
('Eris I-B', 10, 'Jupiter Industries', 'Outstanding Firepower,Sustained Combat', 'Direct-Fire Weapons'),
('Eris I-C', 10, 'Jupiter Industries', 'Sustained Combat', 'Direct-Fire Weapons'),
('Eternal Storm', 2, 'Jupiter Industries', 'Outstanding Firepower', 'Direct-Fire Weapons'),
('FG300-A', 10, 'Dawn Accord', 'Strategy And Support','Direct-Fire Weapons'),
('FG300-B', 10, 'Dawn Accord', 'Sustained Combat','Direct-Fire Weapons'),
('FG300-B', 10, 'Dawn Accord', 'Strategy And Support','Direct-Fire Weapons'),
('Guardian-A', 5, 'Antonios', NULL,'Projectile Weapons'),
('Guardian-B', 5, 'Antonios', 'Strategy and Support','Projectile Weapons'),
('Guardian-C', 5, 'Antonios', 'Outstanding Firepower,Sustained Combat','Direct-Fire Weapons'),
('Io-A',5,'Jupiter Industries','Outstanding Firepower,Sustained Combat','Direct-Fire Weapons'),
('Io-B',5,'Jupiter Industries','Outstanding Firepower,Sustained Combat','Direct-Fire Weapons'),
('Io-C',5,'Jupiter Industries','Outstanding Firepower,Sustained Combat','Direct-Fire Weapons'),
('Jaeger-A',5,'Antonios','Strategy and Support',NULL),
('Jaeger-B',5,'Antonios','Strategy and Support',NULL),
('Janbiya Aer410-A',10,'Jupiter Industries','Strategy and Support,Fighter & Corvette','Projectile Weapons'),
('KCCPV2.0-A',10,'Dawn Accord','Outstanding Firepower,Strategy and Support','Projectile Weapons'),
('KCCPV2.0-B',10,'Dawn Accord','Outstanding Firepower','Direct-Fire Weapons'),
('KCCPV2.0-C',10,'Dawn Accord',NULL,'Direct-Fire Weapons'),
('KCCPV2.0-D',10,'Dawn Accord',NULL,NULL),
('Light Cone-A',5,'Noma',NULL,'Projectile Weapons'),
('Light Cone-B',5,'Noma','Strategy and Support','Projectile Weapons'),
('Light Cone-C',5,'Noma','Outstanding Firepower','Projectile Weapons'),
('Mare Nubium-A',10,'Jupiter Industries','Outstanding Firepower',NULL),
('Mare Nubium-B',10,'Jupiter Industries',NULL,NULL),
('Mare Serenitatis-A',10,'Jupiter Industries','Outstanding Firepower,Sustained Combat','Projectile Weapons'),
('Mare Serenitatis-B',10,'Jupiter Industries','Sustained Combat','Projectile Weapons'),
('Mare Serenitatis-C',10,'Jupiter Industries','Sustained Combat','Projectile Weapons'),
('Mare Tranquillitatis-A',10,'Jupiter Industries','Strategy and Support','Projectile Weapons'),
('Mare Tranquillitatis-B',10,'Jupiter Industries',NULL,'Direct-Fire Weapons'),
('Mare Tranquillitatis-C',10,'Jupiter Industries','Strategy and Support','Projectile Weapons'),
('Marshal Crux',2,'Antonios','Outstanding Firepower,Strategy and Support','Direct-Fire Weapons'),
('Mistral',5,'Antonios','Fighter & Corvette','Direct-Fire Weapons'),
('Nebula Chaser-A',10,'Antonios','Outstanding Firepower,Fighter & Corvette','Direct-Fire Weapons'),
('Nebula Chaser-B',5,'Antonios','Outstanding Firepower,Fighter & Corvette','Direct-Fire Weapons'),
('NOMA M470-A',10,'Noma','Outstanding Firepower',NULL),
('NOMA M470-B',10,'Noma','Strategy and Support',NULL),
('NOMA M470-C',10,'Noma','Strategy and Support',NULL),
('Predator-A',10,'Antonios','Strategy and Support',NULL),
('Predator-B',10,'Antonios','Strategy and Support',NULL),
('Predator-C',10,'Antonios','Strategy and Support',NULL),
('Quaoar-A',10,'Jupiter Industries','Outstanding Firepower','Direct-Fire Weapons'),
('Quaoar-B',10,'Jupiter Industries','Outstanding Firepower','Projectile Weapons'),
('RedBeast 7-13',10,'Noma','Sustained Combat,Strategy and Support,Fighter & Corvette','Projectile Weapons'),
('Reliat-A',10,'Antonios','Outstanding Firepower','Projectile Weapons'),
('Reliat-B',10,'Antonios','Outstanding Firepower','Projectile Weapons'),
('Reliat-C',10,'Antonios','Outstanding Firepower,Sustained Combat','Projectile Weapons'),
('Ruby-A',5,'Noma','Outstanding Firepower','Direct-Fire Weapons'),
('Ruby-B',5,'Noma','Outstanding Firepower','Direct-Fire Weapons'),
('Ruby-C',5,'Noma','Sustained Combat','Projectile Weapons'),
('Sandrake',10,'Noma','Strategy and Support,Fighter & Corvette','Direct-Fire Weapons'),
('SC002',10,'Dawn Accord','Sustained Combat,Strategy and Support,Fighter & Corvette','Direct-Fire Weapons'),
('Silent Assassin',10,'Noma','Fighter & Corvette','Direct-Fire Weapons'),
('Solar Whale',2,'Noma','Strategy and Support',NULL),
