INSERT INTO researchAgreement (shipName, weightData, industryFilter, strategicFilter, tacticalFilter)
VALUES
('AC721-A', 10, 'Dawn Accord', 'Strategy and Support', 'Direct-Fire Weapons'),
('AC721-B', 10, 'Dawn Accord', 'Strategy and Support', 'Projectile Weapons'),
('AC721-D', 10, 'Dawn Accord', 'Strategy and Support',NULL),
('Aldabra-A', 5, 'Noma', 'Outstanding Firepower,Sustained Combat', 'Direct-Fire Weapons'),
('Aldabra-B', 5, 'Noma', 'Outstanding Firepower,Sustained Combat', 'Direct-Fire Weapons'),
('B192 Newland', 10, 'Jupiter Industries', 'Strategy And Support,Fighter & Corvette', 'Direct-Fire Weapons'),
('Balancer Anderson SC020', 10, 'Antonios', 'Sustained Combat,Fighter & Corvette', 'Direct-Fire Weapons'),
('Bullfrog-A', 10, 'Noma', 'Outstanding Firepower,Fighter & Corvette', 'Projectile Weapons'),
('Callisto-A', 2, 'Jupiter Industries', 'Outstanding Firepower', 'Projectile Weapons'),
('Callisto-B', 2, 'Jupiter Industries', 'Outstanding Firepower', 'Projectile Weapons'),
('Callisto-C', 2, 'Jupiter Industries', NULL, 'Projectile Weapons'),
('Carillion-A', 10, 'Antonios', 'Sustained Combat,Strategy And Support', 'Direct-Fire Weapons'),
('Carillion-B', 10, 'Antonios', 'Strategy And Support', 'Direct-Fire Weapons'),
('Carillion-C', 5, 'Antonios', 'Sustained Combat', 'Direct-Fire Weapons'),
('CAS066-A', 10, 'Dawn Accord', 'Outstanding Firepower,Sustained Combat', 'Projectile Weapons'),
('CAS066-B', 10, 'Dawn Accord', 'Outstanding Firepower', 'Direct-Fire Weapons'),
('CAS066-C', 10, 'Dawn Accord', NULL, NULL),
('Cellular Defender', 5, 'Antonios', 'Outstanding Firepower,Fighter & Corvette', 'Projectile Weapons'),
('Ceres-A', 10, 'Jupiter Industries', 'Strategy and Support', NULL),
('Ceres-B', 10, 'Jupiter Industries', 'Strategy and Support', NULL),
('Ceres-C', 10, 'Jupiter Industries', 'Strategy and Support', NULL),
('Chimera-A', 5, 'Noma', 'Outstanding Firepower,Sustained Combat', 'Direct-Fire Weapons'),
('Chimera-B', 5, 'Noma', 'Outstanding Firepower,Sustained Combat', 'Direct-Fire Weapons'),
('Chimera-C', 5, 'Noma', 'Sustained Combat', 'Direct-Fire Weapons'),
('Conamara Chaos-A', 5, 'Jupiter Industries', 'Strategy and Support', 'Direct-Fire Weapons'),
('Conamara Chaos-B', 5, 'Jupiter Industries', 'Outstanding Firepower', 'Direct-Fire Weapons'),
('Constantine the Great', 2, 'Antonios', 'Outstanding Firepower', 'Direct-Fire Weapons'),
('CV-II003', 10, 'Dawn Accord', 'Strategy and Support,Fighter & Corvette', 'Direct-Fire Weapons'),
('CV-M011-A', 10, 'Dawn Accord', 'Outstanding Firepower,Sustained Combat,Strategy And Support,Fighter & Corvette', 'Projectile Weapons'),
('CV-M011-B', 10, 'Dawn Accord', 'Fighter & Corvette', 'Direct-Fire Weapons'),
('CV-T800', 5, 'Dawn Accord', 'Outstanding Firepower,Strategy and Support,Fighter & Corvette', 'Direct-Fire Weapons'),
('CV3000', 2, 'Dawn Accord', 'Strategy and Support', NULL),
('Eris I-A', 10, 'Jupiter Industries', 'Strategy and Support', 'Direct-Fire Weapons'),
('Eris I-B', 10, 'Jupiter Industries', 'Outstanding Firepower,Sustained Combat', 'Direct-Fire Weapons'),
('Eris I-C', 10, 'Jupiter Industries', 'Sustained Combat', 'Direct-Fire Weapons'),
('Eternal Storm', 2, 'Jupiter Industries', 'Outstanding Firepower', 'Direct-Fire Weapons')